language: node_js
node_js:
  - 14
deploy:
  on:
    # 表示在dev分支不走CI
    branch: mian
cache:
  directories:
    - node_modules
before_install:
  - npm install npm-cli-login -S
  - NPM_USER=${npm_user} NPM_PASS=${npm_pass} NPM_EMAIL=${npm_email} npm-cli-login
install:
  - npm install
scripts:
  - npm cache clean --force
  - npm run lint
  - npm run test
  - npm run test:coveralls
  - npm run build:umd:min
  - npm run patch
  - npm publish
